### PR TITLE
Small fix to run migrations queries without a transaction

### LINKED ISSUE #11: "There is no active transaction" error with pdo and mariadb
Sone DBMS does not support DDL statements in a transaction (like Mariadb).
Since PHP 8.0, and error is directly was thrown by PDO in this case : https://github.com/doctrine/migrations/issues/1202

Badly, dbal:schema'update run migration in a transaction

### PR DESCRIPTION
**Pull request by frenchcomp**
Add an option --no-transactions / -n to disable transaction to run migrations queries to fix https://github.com/mnapoli/dbal-schema/issues/11

### CODE REVIEW

File: src/Command/UpdateCommand.php [hunk 1]
```diff
@@ -24,12 +24,17 @@ public function __construct(DbalSchemaCommand $schemaCommand)
     protected function configure(): void
     {
         $this->setName('dbal:schema:update')
-            ->addOption('force', 'f', InputOption::VALUE_NONE);
+            ->addOption('force', 'f', InputOption::VALUE_NONE)
+            ->addOption('no-transactions', 't', InputOption::VALUE_NONE);
```
Comment (mnapoli) [inline src/Command/UpdateCommand.php]: Thanks! Since transactions don't work for Mysql/Mariadb (AFAICT), which are the most popular, could we change this to not use transactions by default?

And then have a `--use-transaction|-t` flag to enable a transaction?

Comment (frenchcomp) [reply src/Command/UpdateCommand.php]: It's done

File: src/DbalSchemaCommand.php [hunk 2]
```diff
@@ -23,15 +23,15 @@ public function __construct(Connection $db, SchemaDefinition $schemaDefinition)
     /**
      * Update the database schema to match the schema definition.
      */
-    public function update(bool $force, OutputInterface $output): void
+    public function update(bool $force, OutputInterface $output, bool $withTransaction = false): void
```
Comment (mnapoli) [inline src/DbalSchemaCommand.php:26]: The default behavior will change to not use transactions. Could we preserve the existing behavior?

Comment (frenchcomp) [reply src/DbalSchemaCommand.php:26]: Yes, but the initial PR was not change the default behavior, but you proposed to switch the default behavior : https://github.com/mnapoli/dbal-schema/pull/12#discussion_r1053433402 Or want you just change behavior of options but not the method ?

Comment (mnapoli) [reply src/DbalSchemaCommand.php:26]: @frenchcomp OMG sorry 😅

I have so many prs and issues to track that I'm not remembering all the details, but thank you for clarifying! That sounds great then, I'll merge!

Comment (frenchcomp) [reply src/DbalSchemaCommand.php:26]: I understand, thanks you for the merge and yours works :)
